import h5py
f_destination = h5py.File("Scenarios_baseline_time_loss.hdf5", "a", libver="latest")
f_src_NWB1 = h5py.File("Scenarios_baseline_time_loss_NW-B1.hdf5","r")
f_src_HEB62 = h5py.File("Scenarios_baseline_time_loss_HE-B62.hdf5","r")
f_src_NIB210 = h5py.File("Scenarios_baseline_time_loss_NI-B210.hdf5","r")
f_src_BYB20 = h5py.File("Scenarios_baseline_time_loss_BY-B20.hdf5","r")
f_src_BYB471 = h5py.File("Scenarios_baseline_time_loss_BY-B471.hdf5","r")
f_src_HEB49 = h5py.File("Scenarios_baseline_time_loss_HE-B49.hdf5","r")
f_src_NWB1.copy(source="NW-B1", dest=f_destination)
f_src_HEB62.copy(source="HE-B62", dest=f_destination)
f_src_NIB210.copy(source="NI-B210", dest=f_destination)
f_src_HEB49.copy(source="HE-B49", dest=f_destination)
f_src_BYB471.copy(source="BY-B471", dest=f_destination)
f_src_BYB20.copy(source="BY-B20", dest=f_destination)
f_destination.close()
f_src_BYB20.close()
f_src_BYB471.close()
f_src_HEB49.close()
f_src_HEB62.close()
f_src_NIB210.close()
f_src_NWB1.close()
